{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: navidrome-oidc
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  clientId: {{ .Values.oidc.clientId | quote }}
  clientSecret: {{ .Values.oidc.clientSecret | quote }}
{{- end }}
