apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data-nfs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
